### ISSUE TITLE
npm start fails due to errors in RequestController.js

### ISSUE THREAD

**Issue by jideokus** [TechForPR/chefsForPR#22]
The catch between 22-27 and 58 - 63 are causing it to fail.

**Comment by dvidsilva** [comment]
Are you using the last master? it seems to work for me, or what's the output you see

**Comment by jideokus** [comment]
Yeah I'm using the last master. This is what I get. I have a workaround to get it started for the time-being.

RequestController.js:26
        ));
        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jideo\Documents\GitHub\chefsForPR\controllers\index.js:2:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by dvidsilva** [comment]
Oh I see now what it is, can you upgrade node to 8? to use some more modern syntax

**Comment by jideokus** [comment]
Ah gotcha. Will do
