### ISSUE TITLE
Build failing during `npm start`

### ISSUE THREAD

**Issue by apravink** [TechForPR/chefsForPR#29]
There are some extra commas in RequestController and DeliveryController that are causing the build to fail at runtime with `npm start`
Getting the error
```
Starting child process with 'node ./bin/www'
/home/abhi/Dev/openSource/chefsForPR/controllers/RequestController.js:26
        ));
        ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/abhi/Dev/openSource/chefsForPR/controllers/index.js:2:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
Program node ./bin/www exited with code 1
```

**Comment by apravink** [comment]
I can work on this if you can assign it to me

**Comment by dvidsilva** [comment]
@apravink can you updgrade your node to version 8? it fails on previous versions because it uses the arrow function syntax in a few places. If you can upgrade that's better. otherwise we can consider not using the new syntax, but there are some improvements in Node8 that are worth having, https://nodejs.org/en/blog/release/v8.0.0/
